# These are supported funding model platforms

# GitHub Sponsors only works if the account is enrolled in GitHub Sponsors.
# Re-enable this after you apply and are approved.
# github: [krillavilla]

ko_fi: krillavilla
# buy_me_a_coffee: your_username
# custom: ["https://your-website.com/donate"]
