# These are supported funding model platforms

github: [krillavilla]  # Replace with your GitHub username if different
ko_fi: krillavilla      # Replace with your Ko-fi username
# buy_me_a_coffee: # Replace with your Buy Me a Coffee username if you set one up
# custom: ["https://your-website.com/donate"]
